EL-Online.Web/Controllers/DashboardController.cs
using EL_Online.Web.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EL_Online.Web.EL_OnlineServiceSite;
using EL_Online.Web.EL_OnlineSeviceEndUser;
using EL_Online.Web.Helpers;
using iTextSharp.text;
using iTextSharp.text.pdf;
using System.IO;
using System.Configuration;
using Antlr.Runtime.Misc;

namespace EL_Online.Web.Controllers
{
    public class DashboardController : BaseController
    {
        // GET: Dashboard
        public ActionResult Index()
        {
            var dashboardModal = new DashboardModal();
            int endUserId;
            try
            {
                endUserId = Convert.ToInt32(Session["EndUserID"]);
            }
            catch (Exception ex)
            { throw ex; }

            // check Session
            if (Session["StrID"] == null || Session["StrID"].ToString() == "")
            {
                return RedirectToAction("Login", "Account", new { area = "" });
            }

            // Data
            try
            {
                if (Request.QueryString.ToString() != "")
                {
                    Session["SiteID"] = Request.QueryString["SiteID"].ToString();
                    Session["HistoryID"] = "0";
                }

                //Data Set user details
                GetEndUserDetails(dashboardModal, endUserId);

                // Data Set current sensor details
                GetSensorDetailsLastDay(dashboardModal, endUserId);

            }
            catch (Exception ex)
            { return RedirectToAction("Login", "Account", new { area = "" }); }


            return View(dashboardModal);
        }

        private void GetEndUserDetails(DashboardModal dashboardModal, int endUserId)
        {
            DataSet endUserInfo;
            using (var endUserService = new EndUserSoapClient())
            {
                endUserInfo = endUserService.GetEndUser(Session["strID"].ToString(), endUserId.ToString());
            }
            if (endUserInfo != null)
            {
                var userInfo = endUserInfo.Tables["tbl"].Rows[0];
                dashboardModal.ZipCode = userInfo["ZipCode"].ToString();
                dashboardModal.SiteName = userInfo["Name"].ToString();
                dashboardModal.Note = userInfo["Note"].ToString();
                dashboardModal.City = userInfo["City"].ToString();
                dashboardModal.Address1 = userInfo["Address1"].ToString();
                dashboardModal.Address2 = userInfo["Address2"].ToString();
                dashboardModal.Objektnamn = userInfo["Opt1"].ToString();
                dashboardModal.Debiteringkod = userInfo["Opt2"].ToString();

            }
        }

        private void GetSensorDetailsLastDay(DashboardModal dashboardModal, int endUserId)
        {
            dashboardModal.SensorCurrentDetailList = new List<SensorCurrentDetailsModal>();
            using (var endUserService = new EndUserSoapClient())
            {
                var dsTmp = endUserService.GetSensorValues(Session["strID"].ToString(), endUserId.ToString());
                var sensorGroupList = (from DataRow dr in dsTmp.Tables[0].DefaultView.Table.Rows
                                       select new
                                       {
                                           SensorGroup = dr[0],
                                           SensorGroupId = dr[1],
                                           SensorId = dr[8],
                                       }).ToList().OrderBy(x => x.SensorGroup);

                var tDate = Convert.ToDateTime(DateTime.Now.Year + "-" + DateTime.Now.Month + "-" + DateTime.Now.Day);
                var fDate = tDate.AddDays(-1);

                DataSet dsSensorHistory;
                foreach (var it in sensorGroupList)
                {
                    dsSensorHistory = endUserService.GetSensorHistoryPeriod(Session["strID"].ToString(), "9", "1440", endUserId.ToString(), it.SensorId.ToString(), fDate.ToString(), tDate.ToString());
                    var avgUsage = dsSensorHistory.Tables[0].DefaultView.Table.AsEnumerable().Select(x => x.Field<double>("Avg")).FirstOrDefault();
                    switch (it.SensorGroupId.ToString())
                    {
                        case "100":
                            // El
                            var sdlEl = new SensorCurrentDetailsModal();
                            sdlEl.TypeName = it.SensorGroup.ToString();
                            sdlEl.Value = Math.Round(avgUsage / 1000).ToString();
                            sdlEl.SensorId = it.SensorId.ToString();
                            sdlEl.UnitName = "kWh";
                            sdlEl.IsElectricity = true;
                            dashboardModal.SensorCurrentDetailList.Add(sdlEl);
                            break;

                        case "110":
                            // Cold water
                            var sdlCold = new SensorCurrentDetailsModal();
                            sdlCold.TypeName = it.SensorGroup.ToString();
                            sdlCold.Value = Math.Round(avgUsage / 1000).ToString();
                            sdlCold.SensorId = it.SensorId.ToString();
                            sdlCold.UnitName = "liter";
                            sdlCold.IsColdWater = true;
                            dashboardModal.SensorCurrentDetailList.Add(sdlCold);
                            break;

                        case "120":
                            // Hot water - formula for conversion !!
                            var sdlHot = new SensorCurrentDetailsModal();
                            sdlHot.UnitName = "liter";
                            sdlHot.TypeName = it.SensorGroup.ToString();
                            sdlHot.Value = Math.Round(avgUsage / 1000).ToString();
                            sdlHot.SensorId = it.SensorId.ToString();
                            sdlHot.IsHotWater = true;
                            dashboardModal.SensorCurrentDetailList.Add(sdlHot);

                            break;

                        case "130":
                            // Heat
                            var sdlHeat = new SensorCurrentDetailsModal();
                            sdlHeat.TypeName = it.SensorGroup.ToString();
                            sdlHeat.Value = Math.Round(avgUsage / 1000).ToString();
                            sdlHeat.SensorId = it.SensorId.ToString();
                            sdlHeat.IsHeat = true;
                            sdlHeat.UnitName = "kWh";
                            dashboardModal.SensorCurrentDetailList.Add(sdlHeat);
                            break;

                        case "140":
                            // Temperatur
                            var sdlTemperatur = new SensorCurrentDetailsModal();
                            sdlTemperatur.TypeName = it.SensorGroup.ToString();
                            sdlTemperatur.UnitName = "grader C";
                            sdlTemperatur.IsTemp = true;
                            sdlTemperatur.Value = Math.Round(avgUsage).ToString();
                            sdlTemperatur.SensorId = it.SensorId.ToString();
                            dashboardModal.SensorCurrentDetailList.Add(sdlTemperatur);
                            break;
                        case "105":
                            // Floor heat
                            var sdlFloorHeat = new SensorCurrentDetailsModal();
                            sdlFloorHeat.TypeName = it.SensorGroup.ToString();
                            sdlFloorHeat.UnitName = "kWh";
                            sdlFloorHeat.IsFloorHeat = true;
                            sdlFloorHeat.Value = Math.Round(avgUsage / 1000).ToString();
                            sdlFloorHeat.SensorId = it.SensorId.ToString();
                            dashboardModal.SensorCurrentDetailList.Add(sdlFloorHeat);
                            break;
                    }

                }

            }



        }

        public JsonResult GetStatisticsByDateRange(string sDate, string eDate, bool isCompare, string iSensorId)
        {
            if (sDate == null || eDate == null)
            {
                var cday = DateTime.Today;
                sDate = cday.AddYears(-1).ToString();
                eDate = cday.ToString();
            }
            var cookieCulture = Request.Cookies["_culture"];
            var endUserId = Convert.ToInt32(Session["EndUserID"]);
            var fDate = DateTime.Parse(sDate);
            var tDate = DateTime.Parse(eDate);
            tDate = tDate.AddDays(2);
            fDate = fDate.AddDays(1);
            var chart = new ChartModel();
            var lastYearFdate = fDate.AddYears(-1);
            var lastYearTdate = tDate.AddYears(-1);

            try
            {   
                DataSet dsSensorHistory;
                DataSet dsSensorHistoryLastPeriod = null;
                using (var endUserService = new EndUserSoapClient())
                {
                   
                    dsSensorHistory = endUserService.GetSensorHistoryPeriod(Session["strID"].ToString(), "9", "1440", endUserId.ToString(), iSensorId, fDate.ToString(), tDate.ToString());

                    if (isCompare)
                    {
                        dsSensorHistoryLastPeriod = endUserService.GetSensorHistoryPeriod(Session["strID"].ToString(), "9", "1440", endUserId.ToString(), iSensorId, lastYearFdate.ToString(), lastYearTdate.ToString());
                    }
                }

                // Selected Date Range
                if ((dsSensorHistory != null) && (dsSensorHistory.Tables.Count != 0))
                {

                    if (dsSensorHistory.Tables[0].Rows.Count != 0)
                    {
                        int iCol = 0;
                        var dataSetForSelectedPeriod = new List<double>();

EL-Online.Web/Views/Shared/_Layout.cshtml
@using EL_Online.Web.Helpers
@model EL_Online.Web.Models.EndUserModal
@{
    var culture = System.Threading.Thread.CurrentThread.CurrentUICulture.Name.ToLowerInvariant();
    var isEnglish = culture == "en-us" ? true : false;
}
@helper selected(string c, string culture)
{
if (c == culture)
{
        @:checked="checked"
    }
}
<!DOCTYPE html>
<html lang="@CultureHelper.GetCurrentNeutralCulture()" dir="@(CultureHelper.IsRighToLeft() ? "rtl" : "ltr")">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="Ascentic">
    <link rel="icon" href="~/Content/images/favicon.ico">
    <title>EL-Online</title>
    @*@Styles.Render("~/Content/css")*@
    <!-- CSS -->
    <link href="~/Content/el-online-style.css" rel="stylesheet" />
    @*@Scripts.Render("~/bundles/modernizr")*@
    <link href="~/Content/bootstrap-datetimepicker.css" rel="stylesheet" />
    @*<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
        <script src="https://code.highcharts.com/highcharts.js"></script>*@
</head>
<body>

    <!-- header starts here -->
    <div id="sideNav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()"><i class="glyphicon glyphicon-remove" aria-hidden="true"></i></a>
        <li>
            <span class="font-style-regular-one">@Resources.Resource.Name </span>
            <span class="paddingLeft font-style-medium-menu">@Model.SiteName</span>
        </li>
        <li>
            <span class="font-style-regular-one">@Resources.Resource.Address </span>
            <span class="paddingLeft font-style-medium-menu">@Model.Address1 @Model.Address2</span>
        </li>
        <li>
            <span class="font-style-regular-one">@Resources.Resource.ZipCode </span>
            <span class="paddingLeft font-style-medium-menu">@Model.ZipCode</span>
        </li>
        <li>
            <span class="font-style-regular-one">@Resources.Resource.City </span>
            <span class="paddingLeft font-style-medium-menu">@Model.City</span>
        </li>
        @if (!string.IsNullOrEmpty(Model.Note))
        {
            <li>
                <span class="font-style-regular-one">@Resources.Resource.Note </span>
                <span class="paddingLeft font-style-medium-menu">@Model.Note</span>
            </li>
        }
        <li id="mobileLanguage">
            <a href="#">
                
                @using (Html.BeginForm("SetCulture", "Dashboard", new {culture = "sv"}))
                {
                    if (culture == "en-us")
                    {
                        isEnglish = true;
                        <button name="submit" value="sv"><img src="~/Content/images/swedish.png" class="paddingRight" width="35" @selected("sv", culture)> SWEDISH</button>
                    }

                }
                @using (Html.BeginForm("SetCulture", "Dashboard", new {culture = "en-us"}))
                {
                    if (culture == "sv")
                    {
                        isEnglish = false;
                        <button name="submit" value="en-us"><img src="~/Content/images/english.png" class="paddingRight" width="35" @selected("en-us", culture)> English</button>
                    }
                }
            </a>
        </li>
        <li id="mobileLogout">
            <span class="paddingLeft font-style-semibold">@Html.ActionLink(Resources.Resource.LogOut, "Login", "Account")</span>
        </li>
    </div>
    <div id="elsystemWrapper">
        <!-- header starts here -->
        <header>
            <nav class="navbar navbar-fixed-top font-style-regular2">
                <div class="container">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="#"><img src="~/Content/images/minImages/el_logo.png" width="150"></a>
                        <ul class="nav navbar-nav pull-right">
                            <li style="margin-top: 5%">
                                @*<a href="#">*@
                                <input type="hidden" id="isEnglishText" value="@culture" />

                                    @using (Html.BeginForm("SetCulture", "Dashboard", new { culture = "sv" }))
                                    {
                                        if (culture == "en-us")
                                        {
                                            isEnglish = true;
                                            <button name="submit" value="sv"><img src="~/Content/images/swedish.png" class="paddingRight" width="35" @selected("sv", culture)> SWEDISH</button>
                                        }

                                    }
                                    @using (Html.BeginForm("SetCulture", "Dashboard", new { culture = "en-us" }))
                                    {
                                        if (culture == "sv")
                                        {
                                            isEnglish = false;
                                            <button name="submit" value="en-us"><img src="~/Content/images/english.png" class="paddingRight" width="35" @selected("en-us", culture)> ENGLISH</button>
                                        }
                                    }
                               @* </a>*@

                            </li>
                            <li>@Html.ActionLink(Resources.Resource.LogOut, "Login", "Account")</li>
                            <li onclick="openNav()"><a href="#"> <span class="paddingRight"> @Resources.Resource.More</span> <i class="glyphicon glyphicon-option-vertical" aria-hidden="true"></i></a></li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <!-- print section starts here -->
        <section id="printSection" class="container">
            <div class="font-style-semibold pull-left"> @Model.SiteName</div>
            <input class="btn btn-primary btn-sm font-style-regular-one pull-right" type="submit" value="@Resources.Resource.PrintThisPage" onclick="showPrintSetting()" />
            <div class="col-xs-12 " id="printSettingPannel" style="display: none">
                <div class="col-xs-12 col-sm-4 ">
                    <div class="form-group">
                        <div class="input-group date" id="pdfStartDate">
                            <input type="text" id="pdfStartDate-input" class="form-control">
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-4">
                    <div class="form-group">
                        <div class="input-group date" id="pdfEndDate">
                            <input type="text" id="pdfEndDate-input" class="form-control">
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-4 form-group">
                    <input class="btn btn-primary btn-sm font-style-regular-one" type="submit" id="printPdfButton" value="@Resources.Resource.PrintNow" onclick="printPdf()">
                </div>
                <a href="#" style="display: none" id="pdfLink"></a>
            </div>

        </section>
        <!-- print section ends here -->
        <!-- consumption section starts here -->
        <section id="consumptionSection" class="container">
            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                @RenderBody()
                <hr />
                <footer>
                    <div class="container">
                        <span class="font-style-regular-three">&copy; @DateTime.Now.Year - ELsystem. All Rights Reserved.</span>
                    </div>
                </footer>
            </div>
        </section>
    </div>

    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")*@
    <!-- javascript -->
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/highcharts-more.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    @*<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>*@
    <script src="~/Scripts/moment.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap-datetimepicker.min.js"></script>
    <script src="~/Scripts/locale-sv.js"></script>
    <script src="~/Scripts/script.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>